version: "3.8"

services:

    balasolu:
        build:
            context: .
            dockerfile: etc/docker/balasolu-debug.Dockerfile
            target: production
        ports:
            - 3000:3000
        restart: always

    nginx:
        build:
            context: .
            dockerfile: etc/docker/nginx-debug.Dockerfile
        ports:
            - 80:80
            - 443:443
        restart: always